export const notificationData = [
  {
    external_id: '6',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '6',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'read',
    priority: 'medium',
    metadata: {
      sourceType: 'participation',
      source_id: '1',
      urlAction: '/dashboard/nextEvents/1',
      extra: {
        eventName: 'Tournoi de Tennis',
        event_id: 1,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '7',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'participation',
      source_id: '2',
      urlAction: '/dashboard/nextEvents/1',
      extra: {
        eventName: 'Tournoi de Tennis',
        eventTime: '14h00',
        event_id: 1,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '8',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'event',
      source_id: '3',
      urlAction: '/dashboard/pastParticipations/2',
      extra: {
        eventName: 'Marathon de Paris',
        eventDate: '25 mars 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '9',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'event',
      source_id: '2',
      urlAction: '/events/2',
      extra: {
        eventName: 'Randonnée Pyrénées',
        changes: 'date, lieu de départ',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '10',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '5',
      urlAction: '/events/5',
      extra: {
        eventName: 'Festival de musique',
        eventDate: '15 juin 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '11',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '12',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'participation',
      source_id: '9',
      urlAction: '/dashboard/nextEvents/3',
      extra: {
        eventName: "Course d'orientation",
        eventTime: '09h30',
        event_id: 3,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '13',
    template_name: 'event-announcement',
    type: 'event',
    status: 'read',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '6',
      urlAction: '/events/6',
      extra: {
        eventName: 'Atelier cuisine',
        eventDate: '10 avril 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '14',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    metadata: {
      sourceType: 'participation',
      source_id: '11',
      urlAction: '/dashboard/nextEvents/3',
      extra: {
        eventName: "Course d'orientation",
        event_id: 3,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '15',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'event',
      source_id: '6',
      urlAction: '/events/6',
      extra: {
        eventName: 'Atelier cuisine',
        changes: 'horaire, nombre de places',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '16',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'event',
      source_id: '4',
      urlAction: '/events/4',
      extra: {
        eventName: 'Nettoyage de plage',
        eventDate: '5 mai 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '17',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '18',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '7',
      urlAction: '/events/7',
      extra: {
        eventName: 'Salon du livre',
        eventDate: '22 mai 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '19',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'read',
    priority: 'low',
    metadata: {
      sourceType: 'participation',
      source_id: '15',
      urlAction: '/dashboard/nextEvents/6',
      extra: {
        eventName: 'Atelier cuisine',
        eventTime: '18h00',
        event_id: 6,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '20',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    metadata: {
      sourceType: 'participation',
      source_id: '16',
      urlAction: '/dashboard/nextEvents/6',
      extra: {
        eventName: 'Atelier cuisine',
        event_id: 6,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'rating-received',
    type: 'event',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '1',
      urlAction: '/dashboard/pastParticipations/1',
      extra: {
        rating: 4,
        eventName: 'Tournoi de Tennis',
        volunteer_id: 6,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'participation',
      source_id: '7',
      urlAction: '/dashboard/pending',
      extra: {
        volunteerName: 'Marie Dupont',
        eventName: 'Randonnée Pyrénées',
        event_id: 2,
        volunteer_id: 13,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '4',
    template_name: 'participation-cancelled',
    type: 'participation',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'participation',
      source_id: '12',
      urlAction: '/dashboard/nextEvents/4',
      extra: {
        volunteerName: 'Pierre Martin',
        eventName: 'Nettoyage de plage',
        event_id: 4,
        volunteer_id: 16,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '5',
    template_name: 'participation-updated',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    metadata: {
      sourceType: 'participation',
      source_id: '4',
      urlAction: '/dashboard/nextEvents/1',
      extra: {
        volunteerName: 'Sophie Bernard',
        eventName: 'Tournoi de Tennis',
        event_id: 1,
        volunteer_id: 15,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'rating-received',
    type: 'event',
    status: 'read',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '3',
      urlAction: '/dashboard/pastParticipations/3',
      extra: {
        rating: 5,
        eventName: "Course d'orientation",
        volunteer_id: 11,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    metadata: {
      sourceType: 'participation',
      source_id: '14',
      urlAction: '/dashboard/pending',
      extra: {
        volunteerName: 'Lucas Petit',
        eventName: 'Festival de musique',
        event_id: 5,
        volunteer_id: 18,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '21',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'event',
      source_id: '8',
      urlAction: '/events/8',
      extra: {
        eventName: 'Yoga en plein air',
        eventDate: '1er juin 2026',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '22',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '23',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    metadata: {
      sourceType: 'participation',
      source_id: '23',
      urlAction: '/dashboard/nextEvents/8',
      extra: {
        eventName: 'Yoga en plein air',
        eventTime: '10h00',
        event_id: 8,
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '24',
    template_name: 'event-updated',
    type: 'event',
    status: 'read',
    priority: 'high',
    metadata: {
      sourceType: 'event',
      source_id: '10',
      urlAction: '/events/10',
      extra: {
        eventName: 'Concours de photo',
        changes: 'thème, date limite',
      },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
];
