export const notificationData = [
  {
    external_id: '6',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/profile',
    metadata: { sourceType: 'system', source_id: 'onboarding' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '6',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'read',
    priority: 'medium',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/1',
    metadata: {
      sourceType: 'participation',
      source_id: '1',
      extra: { event_id: 1 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '7',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/1',
    metadata: {
      sourceType: 'participation',
      source_id: '2',
      extra: { event_id: 1 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '8',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/dashboard/pastParticipations/2',
    metadata: { sourceType: 'event', source_id: '3' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '9',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/events/2',
    metadata: { sourceType: 'event', source_id: '2' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '10',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/events/5',
    metadata: { sourceType: 'event', source_id: '5' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '11',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/profile',
    metadata: { sourceType: 'system', source_id: 'onboarding' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '12',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/3',
    metadata: {
      sourceType: 'participation',
      source_id: '9',
      extra: { event_id: 3 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '13',
    template_name: 'event-announcement',
    type: 'event',
    status: 'read',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/events/6',
    metadata: { sourceType: 'event', source_id: '6' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '14',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/3',
    metadata: {
      sourceType: 'participation',
      source_id: '11',
      extra: { event_id: 3 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '15',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/events/6',
    metadata: { sourceType: 'event', source_id: '6' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '16',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/events/4',
    metadata: { sourceType: 'event', source_id: '4' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '17',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/profile',
    metadata: { sourceType: 'system', source_id: 'onboarding' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '18',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/events/7',
    metadata: { sourceType: 'event', source_id: '7' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '19',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'read',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/6',
    metadata: {
      sourceType: 'participation',
      source_id: '15',
      extra: { event_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '20',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/6',
    metadata: {
      sourceType: 'participation',
      source_id: '16',
      extra: { event_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'rating-received',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/pastParticipations/1',
    metadata: {
      sourceType: 'event',
      source_id: '1',
      extra: { volunteer_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/dashboard/pending',
    metadata: {
      sourceType: 'participation',
      source_id: '7',
      extra: { event_id: 2, volunteer_id: 13 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '4',
    template_name: 'participation-cancelled',
    type: 'participation',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/4',
    metadata: {
      sourceType: 'participation',
      source_id: '12',
      extra: { event_id: 4, volunteer_id: 16 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '5',
    template_name: 'participation-updated',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/1',
    metadata: {
      sourceType: 'participation',
      source_id: '4',
      extra: { event_id: 1, volunteer_id: 15 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'rating-received',
    type: 'event',
    status: 'read',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/pastParticipations/3',
    metadata: {
      sourceType: 'event',
      source_id: '3',
      extra: { volunteer_id: 11 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/dashboard/pending',
    metadata: {
      sourceType: 'participation',
      source_id: '14',
      extra: { event_id: 5, volunteer_id: 18 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '21',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/events/8',
    metadata: { sourceType: 'event', source_id: '8' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '22',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/profile',
    metadata: { sourceType: 'system', source_id: 'onboarding' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '23',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: 'inApp',
    urlAction: '/dashboard/nextEvents/8',
    metadata: {
      sourceType: 'participation',
      source_id: '23',
      extra: { event_id: 8 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '24',
    template_name: 'event-updated',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: 'inApp',
    urlAction: '/events/10',
    metadata: { sourceType: 'event', source_id: '10' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
];
