export const notificationData = [
  {
    external_id: '6',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '6',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'read',
    priority: 'medium',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '1',
      urlAction: '/dashboard/nextEvents/1',
      extra: { event_id: 1 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '7',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '2',
      urlAction: '/dashboard/nextEvents/1',
      extra: { event_id: 1 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '8',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'event',
      source_id: '3',
      urlAction: '/dashboard/pastParticipations/2',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '9',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '2', urlAction: '/events/2' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '10',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '5', urlAction: '/events/5' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '11',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '12',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '9',
      urlAction: '/dashboard/nextEvents/3',
      extra: { event_id: 3 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '13',
    template_name: 'event-announcement',
    type: 'event',
    status: 'read',
    priority: 'low',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '6', urlAction: '/events/6' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '14',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '11',
      urlAction: '/dashboard/nextEvents/3',
      extra: { event_id: 3 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '15',
    template_name: 'event-updated',
    type: 'event',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '6', urlAction: '/events/6' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '16',
    template_name: 'event-cancelled',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '4', urlAction: '/events/4' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '17',
    template_name: 'welcome',
    type: 'system',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '18',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '7', urlAction: '/events/7' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '19',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'read',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '15',
      urlAction: '/dashboard/nextEvents/6',
      extra: { event_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '20',
    template_name: 'participation-accepted',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '16',
      urlAction: '/dashboard/nextEvents/6',
      extra: { event_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'rating-received',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'event',
      source_id: '1',
      urlAction: '/dashboard/pastParticipations/1',
      extra: { volunteer_id: 6 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '7',
      urlAction: '/dashboard/pending',
      extra: { event_id: 2, volunteer_id: 13 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '4',
    template_name: 'participation-cancelled',
    type: 'participation',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '12',
      urlAction: '/dashboard/nextEvents/4',
      extra: { event_id: 4, volunteer_id: 16 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '5',
    template_name: 'participation-updated',
    type: 'participation',
    status: 'unread',
    priority: 'medium',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '4',
      urlAction: '/dashboard/nextEvents/1',
      extra: { event_id: 1, volunteer_id: 15 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '3',
    template_name: 'rating-received',
    type: 'event',
    status: 'read',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'event',
      source_id: '3',
      urlAction: '/dashboard/pastParticipations/3',
      extra: { volunteer_id: 11 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '2',
    template_name: 'participation-request',
    type: 'participation',
    status: 'unread',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '14',
      urlAction: '/dashboard/pending',
      extra: { event_id: 5, volunteer_id: 18 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '21',
    template_name: 'event-announcement',
    type: 'event',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '8', urlAction: '/events/8' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '22',
    template_name: 'welcome',
    type: 'system',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: {
      sourceType: 'system',
      source_id: 'onboarding',
      urlAction: '/profile',
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '23',
    template_name: 'event-reminder',
    type: 'participation',
    status: 'unread',
    priority: 'low',
    channel: ['inApp'],
    metadata: {
      sourceType: 'participation',
      source_id: '23',
      urlAction: '/dashboard/nextEvents/8',
      extra: { event_id: 8 },
    },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
  {
    external_id: '24',
    template_name: 'event-updated',
    type: 'event',
    status: 'read',
    priority: 'high',
    channel: ['inApp'],
    metadata: { sourceType: 'event', source_id: '10', urlAction: '/events/10' },
    createdAt: new Date('2025-11-03T13:43:28'),
  },
];
