export const recipientData = [
  { external_id: '2', name: 'Organisateur 1', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '3', name: 'Organisateur 2', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '4', name: 'Organisateur 3', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '5', name: 'Organisateur 4', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '6', name: 'Bénévole 1', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '7', name: 'Bénévole 2', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '8', name: 'Bénévole 3', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'system'] } },
  { external_id: '9', name: 'Bénévole 4', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'system'] } },
  { external_id: '10', name: 'Bénévole 5', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '11', name: 'Bénévole 6', preferences: { enabledChannels: ['inApp'], enabledTypes: ['system'] } },
  { external_id: '12', name: 'Bénévole 7', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '13', name: 'Bénévole 8', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '14', name: 'Bénévole 9', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'system', 'participation'] } },
  { external_id: '15', name: 'Bénévole 10', preferences: { enabledChannels: ['inApp'], enabledTypes: ['participation', 'event', 'system'] } },
  { external_id: '16', name: 'Bénévole 11', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '17', name: 'Bénévole 12', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'system'] } },
  { external_id: '18', name: 'Bénévole 13', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '19', name: 'Bénévole 14', preferences: { enabledChannels: ['inApp'], enabledTypes: ['participation', 'system'] } },
  { external_id: '20', name: 'Bénévole 15', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '21', name: 'Bénévole 16', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'system'] } },
  { external_id: '22', name: 'Bénévole 17', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['system'] } },
  { external_id: '23', name: 'Bénévole 18', preferences: { enabledChannels: ['inApp'], enabledTypes: ['event', 'participation', 'system'] } },
  { external_id: '24', name: 'Bénévole 19', preferences: { enabledChannels: ['inApp', 'email'], enabledTypes: ['event','system'] } },
];