export const templateData = [
  {
    name: 'welcome',
    type: 'system',
    channel: 'inApp',
    title: 'Bienvenue',
    content: 'Pensez à compléter votre profil pour pouvoir postuler à un event',
    metadata: {},
  },
  {
    name: 'participation-accepted',
    type: 'participation',
    channel: 'inApp',
    title: 'Validation',
    content: 'Votre participation a été acceptée',
    metadata: { event_id: 'number', participation_id: 'number' },
  },
  {
    name: 'event-reminder',
    type: 'participation',
    channel: 'inApp',
    title: 'Rappel',
    content: "N'oubliez pas votre événement demain",
    metadata: { event_id: 'number', participation_id: 'number' },
  },
  {
    name: 'event-cancelled',
    type: 'event',
    channel: 'inApp',
    title: 'Annulation',
    content: "L'événement a été annulé",
    metadata: { event_id: 'number' },
  },
  {
    name: 'event-updated',
    type: 'event',
    channel: 'inApp',
    title: 'Mise à jour',
    content: "Des détails de l'évènement ont changés",
    metadata: { event_id: 'number' },
  },
  {
    name: 'event-announcement',
    type: 'event',
    channel: 'inApp',
    title: 'Annonce',
    content: 'Nouvel événement disponible dans votre région',
    metadata: { event_id: 'number' },
  },
  {
    name: 'rating-received',
    type: 'event',
    channel: 'inApp',
    title: 'Nouvelle évaluation',
    content: 'Vous avez reçu une note',
    metadata: { event_id: 'number', volunteer_id: 'number' },
  },
  {
    name: 'participation-request',
    type: 'participation',
    channel: 'inApp',
    title: 'Demande',
    content: "Vous avez une nouvelle demande d'inscription en attente",
    metadata: {
      event_id: 'number',
      volunteer_id: 'number',
      participation_id: 'number',
    },
  },
  {
    name: 'participation-cancelled',
    type: 'participation',
    channel: 'inApp',
    title: 'Désinscription',
    content: "Un bénévole s'est désinscrit",
    metadata: {
      event_id: 'number',
      volunteer_id: 'number',
      participation_id: 'number',
    },
  },
  {
    name: 'participation-updated',
    type: 'participation',
    channel: 'inApp',
    title: 'Modification',
    content: 'Un bénévole a modifié son inscription',
    metadata: {
      event_id: 'number',
      volunteer_id: 'number',
      participation_id: 'number',
    },
  },
];
